language: bash

os:
  - linux

dist: xenial
sudo: require

git:
  depth: false
  submodules: false

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y --no-install-recommends texlive-fonts-recommended texlive-latex-extra texlive-fonts-extra dvipng texlive-latex-recommended

script:
  - mkdir _build
  - pdflatex -interaction=nonstopmode -halt-on-error -output-directory _build TheHistoryofEniac.tex

branches:
  only:
    master

notifications:
    email:
      on_success: always
      on_failure: always
